." ============================== 헤더 ==============================
.TH arkzip 1 "7월 2014" "version $VERSION"

." ============================== 이름 ==============================
.SH 이름
arkzip - 압축 파일을 압축 해제한다.

." ============================== 사용법 ==============================
.SH 사용법
arkzip
.BR [ 옵션... ]
.BR [ 대상... ]

." ============================== 설명 ==============================
.SH 설명
.B arkzip
은 ArkLibrary를 사용한 압축파일 압축해제 프로그램입니다. egg, alz를 포함한 다양한 압축 형식을 압축 해제 할 수 있으며, 한글 인코딩으로 목록이 인코딩된 압축 파일도 올바르게 압축 해제 할 수 있습니다. 또한, 암호가 걸린 압축 파일도 압축 해제 할 수 있습니다.
.PP 
이 프로그램은 다음 압축 형식에 대한 압축 해제를 지원합니다. zip, alz, egg, tar, bh, 7z, wim, rar, arj, ace, cab, lzh, gz, bz2, iso, udf, img, xz, z, lzma, j2j, nsis.
.PP
중복 파일이 발견되면 사용자에게 묻지 않고 새로운 이름을 지정합니다.
.PP
만약 cui에서 비 터미널 환경에서 작업하게 될시, 암호 입력과 같은 작업은 자동으로 무시됩니다. 이전에 암호가 설정되어 있다면 해당 암호를 대입하고, 아니라면 암호가 설정된 파일은 건너뛰고 작업합니다.
.PP
입력된 암호가 잘못된 암호라면, 암호가 올바를때까지 다시 물어보게 됩니다. 이는 옵션을 통해 지정된 암호에 대해서도 마찬가지로 적용됩니다. 만약, 암호 입력을 취소하려 한다면 아무값도 입력하지 않으면 해당 파일은 건너뛰게 됩니다.
.PP
arkzip의 gui에는 일시정지 기능이 포함되어 있습니다. 그러나, cui와 none에는 별도의 일시정지 프로세스가 포함되어 있지 않습니다.

." ============================== 옵션 ==============================
.SH 옵션
." >>> 일반 옵션들 <<<
.PP
.B 일반 옵션들:
.TP
\fB\-h\fR, \fB\-\-help
도움말 페이지를 표시하고 종료합니다.
.TP
\fB\-i\fR, \fB\-\-interface\fR 타입
인터페이스를 지정합니다. 기본 값은 cui입니다.
 \fBgui\fR : GUI로 사용자와 상호작용합니다. 이 타입을 선택하면 창을 통해 현재 작업 현황을 확인하고 제어 할 수 있습니다.
 \fBcui\fR : CUI로 사용자와 상호작용합니다. 이 타입을 선택하면 터미널을 통해 현재 작업 현황을 확인하고 제어 할 수 있습니다.
 \fBnone\fR : 사용자와 상호 작용하지 않습니다. 사용자의 응답이 필요한 작업은 건너뜁니다. 예컨데, 패스워드가 필요한 파일은 압축해제하지 않고 건너뜁니다. 오류 메시지는 출력하지 않습니다. 단순히 사용자가 받을수 있는 결과는 종료 코드 뿐입니다.
 
." >>> 압축 해제 옵션들 <<<
.PP
.B 압축 해제 옵션들:
.TP
\fB\-c\fR, \fB\-\-codepage\fR 종류
압축 해제 및 암호 지정에 사용할 코드 페이지를 지정합니다.
 \fButf8\fR : UTF-8인 경우. 압축 파일의 파일 목록, 암호의 인코딩을 \fIUTF-8\fR로 해석합니다.
 \fBkor\fR : 한글인 경우. 압축 파일의 파일 목록, 암호의 인코딩을 \fIEUC-KR\fR, \fICP949\fR로 해석합니다.
 \fBjpn\fR : 일본어인 경우. 압축 파일의 파일 목록, 암호의 인코딩을 \fISHIFT-JIS\fR, \fICP932\fR로 해석합니다.
.TP
\fB\-t\fR, \fB\-\-test
압축파일을 메모리에서 압축 해제합니다. 이 옵션을 사용할 때는 목적지 주소를 적지 않습니다.
 
." >>> 저장 경로 옵션들 <<<
.PP
.B 저장 경로 옵션들:
.TP
\fB\-s\fR, \fB\-\-separate
각각의 파일을 파일 명으로 만들어진 폴더에 저장합니다. 예컨데, 저장 경로가 .이고, 파일 명이 arkzip.7z이라면, 압축 파일이 해제될 경로는 ./arkzip입니다. 만약, 중복 파일이 존재한다면 ./arkzip (d1)식으로 지정되게 됩니다.
.TP
\fB\-O\fR, \fB\-\-output-dir\fR 경로
저장할 경로를 설정합니다. 기본값은 현재경로(.)입니다.
.TP
\fB\--link
 각 압축 파일이 위치한 디렉토리에 압축 해제합니다. 만약 이 옵션이 지정된다면, --output-dir옵션은 무시됩니다. 예컨데, `/home/tester/a.zip'이 압축 대상으로 지정되었다면 이 파일은 `/home/tester'에 압축 해제됩니다.
 이 옵션은 다른 저장 경로 옵션과 함께 쓸 수 있습니다. 예를 들어 `arkzip --link -s /tmp/test.egg'의 저장 경로는 `/tmp/test'입니다.

." >>> 암호 옵션들 <<<
.PP
.B 암호 옵션들:
.TP
\fB\-k\fR, \fB\-\-key\fR 암호
압축 해제에 사용할 암호를 지정합니다. 예를 들어, `-k test1234'식으로 사용합니다.
.TP
\fB\-K\fR, \fB\-\-key-hex\fR 암호
HEX로 인코딩된 암호를 입력 받습니다. 예를 들어, `-K 2b2f532a323334'식으로 사용합니다. 이 값은 `+/S*234'와 같습니다.

." ============================== 종료코드 ==============================
.SH 종료코드
만약 오류가 발생한다면 0 이상의 값을 가진 종료코드를 반환합니다.
.PP
1.x.x 버전대의 프로그램이 중복 파일에 대한 회피 작업을 오류로 간주하던것과 달리 2.x.x버전대에서는 정상적인 동작으로 간주합니다. 종료 코드는 별다른 오류가 발생하지 않는다면 0으로 설정됩니다.
.PP
0이상의 종료 코드 - 즉, 오류 코드의 각 값들에 대한 의미는 아직 고정되지 않았습니다. 다음 업데이트시 변경 될 수 있습니다.
.PP
만약 arkzip의 gui에서 중단 기능을 사용하면 종료 코드는 무조건 0 이상입니다.

." ============================== 라이브러리 버전 정보 ==============================
.SH 라이브러리 버전 정보
ArkLibrary v5.0.2.3
.PP
그 외의 라이브러리 버전 정보는 의존 패키지를 따릅니다.

." ============================== 저작권 ==============================
.SH 저작권
이 프로그램은 LGPL 3.0을 따릅니다. 자세한 내용은
.I /usr/share/arkzip/COPYING
을 참조하여 주세요.
.PP
이 프로그램에 사용된 라이브러리에 대한 라이센스 정보는 
.I /usr/share/arkzip/License.txt
를 참조하여 주세요.

." ============================== 홈페이지 ==============================
.SH 홈페이지
https://github.com/Thestars3/arkzip

." ============================== 제작자 ==============================
.SH 제작자
별님 <w7dn1ng75r@gmail.com>
