." ============================== 헤더 ==============================
.TH arkzip 1 "7월 2014" "version $VERSION"

." ============================== 이름 ==============================
.SH 이름
arkzip - 압축 파일을 압축 해제한다.

." ============================== 사용법 ==============================
.SH 사용법
arkzip
.BR [ 옵션... ]
.BR [ 대상... ]

." ============================== 설명 ==============================
.SH 설명
.B arkzip
은 ArkLibrary를 사용한 압축파일 압축해제 프로그램입니다. egg, alz를 포함한 다양한 압축 형식을 압축 해제 할 수 있으며, 한글 인코딩으로 목록이 인코딩된 압축 파일도 올바르게 압축 해제 할 수 있습니다. 또한, 암호가 걸린 압축 파일도 압축 해제 할 수 있습니다.
.PP 
이 프로그램은 다음 압축 형식에 대한 압축 해제를 지원합니다. zip, alz, egg, tar, bh, 7z, wim, rar, arj, cab, lzh, gz, bz2, iso, img, xz, z, lzma, j2j, hv3.
.PP
중복 파일이 발견되면 사용자에게 묻지 않고 새로운 이름을 지정합니다.
.PP
만약 cui에서 비 터미널 환경에서 작업하게 될시, 암호 입력과 같은 작업은 자동으로 무시됩니다. 이전에 암호가 설정되어 있다면 해당 암호를 대입하고, 아니라면 암호가 설정된 파일은 건너뛰고 작업합니다.
.PP
입력된 암호가 잘못된 암호라면, 암호가 올바를때까지 다시 물어보게 됩니다. 이는 옵션을 통해 지정된 암호에 대해서도 마찬가지로 적용됩니다. 만약, 암호 입력을 취소하려 한다면 아무값도 입력하지 않으면 해당 파일은 건너뛰게 됩니다.
.PP
하나 초과의 압축 파일을 일괄 압축 해제 하던 중 입력받은 암호는 이후 해제되는 압축 파일에 적용되게 됩니다.
.PP
arkzip의 gui에는 일시정지 기능이 포함되어 있습니다. 그러나, cui와 none에는 별도의 일시정지 프로세스가 포함되어 있지 않습니다.

." ============================== 옵션 ==============================
.SH 옵션
." >>> 일반 옵션들 <<<
.PP
.B 일반 옵션들:
.TP
\fB\-h\fR, \fB\-\-help
도움말 페이지를 표시하고 종료합니다.
.TP
\fB\-i\fR, \fB\-\-interface\fR 타입
인터페이스를 지정합니다. 기본 값은 cui입니다.
 \fBgui\fR : GUI로 사용자와 상호작용합니다. 이 타입을 선택하면 창을 통해 현재 작업 현황을 확인하고 제어 할 수 있습니다.
 \fBcui\fR : CUI로 사용자와 상호작용합니다. 이 타입을 선택하면 터미널을 통해 현재 작업 현황을 확인하고 제어 할 수 있습니다.
 \fBnone\fR : 사용자와 상호 작용하지 않습니다. 사용자의 응답이 필요한 작업은 건너뜁니다. 예컨데, 패스워드가 필요한 파일은 압축해제하지 않고 건너뜁니다. 오류 메시지는 출력하지 않습니다. 단순히 사용자가 받을수 있는 결과는 종료 코드 뿐입니다.
 
." >>> 압축 해제 옵션들 <<<
.PP
.B 압축 해제 옵션들:
.TP
\fB\-c\fR, \fB\-\-codepage\fR 종류
압축 해제에 사용할 코드 페이지를 지정합니다. 파일 목록만 지정된 코드 페이지로 처리됩니다. `CP + [코드페이지 번호]' 형식으로 사용 가능한 코드 페이지 목록에 존재하지 않는 코드 페이지를 지정 할 수 있습니다. auto는 기본 설정된 값을 사용합니다. 대소문자를 구분하지 않습니다.
.TP
\fB\-\-codepage-list
사용 가능한 코드 페이지 목록을 출력합니다. 각 단락은 동일한 코드 페이지를 가리킵니다. 쉼표로 구분된 이름 중 각 줄의 첫번째 이름은 코드 페이지 번호를 의미하고, 두번째 이름 부터는 해당 코드페이지에 대한 별명을 의미합니다.
.TP
\fB\-t\fR, \fB\-\-test
압축파일을 메모리에서 압축 해제합니다. 이 옵션을 사용할 때는 목적지 주소를 적지 않습니다.
 
." >>> 저장 경로 옵션들 <<<
.PP
.B 저장 경로 옵션들:
.TP
\fB\-s\fR, \fB\-\-separate
각각의 파일을 파일 명으로 만들어진 폴더에 저장합니다. 예컨데, 저장 경로가 .이고, 파일 명이 arkzip.7z이라면, 압축 파일이 해제될 경로는 ./arkzip입니다. 만약, 중복 파일이 존재한다면 ./arkzip (d1)식으로 지정되게 됩니다.
.TP
\fB\-O\fR, \fB\-\-output-dir\fR 경로
저장할 경로를 설정합니다. 기본값은 현재경로(.)입니다.
.TP
\fB\-\-link
 각 압축 파일이 위치한 디렉토리에 압축 해제합니다. 만약 이 옵션이 지정된다면, --output-dir옵션은 무시됩니다. 예컨데, `/home/tester/a.zip'이 압축 대상으로 지정되었다면 이 파일은 `/home/tester'에 압축 해제됩니다.
 이 옵션은 다른 저장 경로 옵션과 함께 쓸 수 있습니다. 예를 들어 `arkzip --link -s /tmp/test.egg'의 저장 경로는 `/tmp/test'입니다.

." >>> 암호 옵션들 <<<
.PP
.B 암호 옵션들:
.TP
\fB\-k\fR, \fB\-\-key\fR 암호
압축 해제에 사용할 암호를 지정합니다. 예를 들어, `-k test1234'식으로 사용합니다.
.TP
\fB\-K\fR, \fB\-\-key-hex\fR 암호
HEX로 인코딩된 암호를 입력 받습니다. 예를 들어, `-K 2b2f532a323334'식으로 사용합니다. 이 값은 `+/S*234'와 같습니다.
.TP
\fB\-\-skip-pass
암호를 물어보지 않게 합니다. 이 옵션을 사용하면, 이전에 지정된 암호가 틀렸더라도 새로운 암호를 암호를 물어보지 않습니다.

." ============================== 종료코드 ==============================
.SH 종료 코드
.PP
1.x.x 버전대의 프로그램이 중복 파일에 대한 회피 작업을 오류로 간주하던것과 달리 2.x.x버전대에서는 정상적인 동작으로 간주합니다. 종료 코드는 별다른 오류가 발생하지 않는다면 0으로 설정됩니다.
.PP
\fB0\fR	오류 없음.
.PP
\fB1\fR	없는 옵션을 사용한 경우.
.PP
\fB2\fR	옵션 값의 오류가 발생한 경우.
.PP
\fB3\fR	옵션 값이 없을 경우.
.PP
\fB4\fR	옵션과 관련된 기타 오류.
.PP
\fB5\fR	옵션에서 정의되지 않은 코드 페이지 지정.
.PP
\fB6\fR	옵션에서 정의되지 않은 인터페이스 지정.
.PP
\fB7\fR	압축을 풀 경로에 문제가 있음.
.PP
\fB8\fR	\-\-key 옵션과 \-\-hex-key 옵션의 동시 사용.
.PP
\fB9\fR	압축 해제 대상으로 지정된 파일을 찾을수 없음.
.PP
\fB10\fR	압축 해제 대상으로 지정된 파일은 파일이 아님.
.PP
\fB11\fR	cui 또는 gui 프로그램과 프로세서를 대치하던 중 오류가 발생.
.PP
\fB12\fR	작업 도중 강제 중단됨. gui에서 중지 명령등으로 인해 발생됨.
.PP
\fB13\fR	옵션 처리 프로세서에서 알 수 없는 문제가 발생했음.
.PP
\fB14\fR	압축 파일에 대한 분할된 폴더를 생성하는데 실패했음.
.PP
\fB15\fR	파일을 여는데 문제가 생겼음.
.PP
\fB16\fR	Ark 라이브러리를 로드하는데 문제가 생김.
.PP
\fB17\fR	파일을 여는데 실패 했습니다.
.PP
\fB18\fR	시그니처를 읽는데 실패했습니다.
.PP
\fB19\fR	컨테이너 헤더가 손상 되었습니다.
.PP
\fB20\fR	파일명 길이에 문제가 있습니다.
.PP
\fB21\fR	파일이름을 읽는데 실패 했습니다.
.PP
\fB22\fR	확장 필드의 길이를 알 수 없습니다.
.PP
\fB23\fR	확장 필드를 읽는데 실패했습니다.
.PP
\fB24\fR	중앙 디렉토리 정보를 읽는데 실패하였습니다. (zip 포멧)
.PP
\fB25\fR	파일명 길이 정보가 잘못되었습니다.
.PP
\fB26\fR	확장 필드 정보 길이가 잘못되었습니다. (zip 포멧)
.PP
\fB27\fR	Comment 정보 길이가 잘못되었습니다.
.PP
\fB28\fR	컨테이너의 헤더에 문제가 있습니다.
.PP
\fB29\fR	메모리 할당에 실패했습니다.
.PP
\fB30\fR	압축 데이타 읽기에 실패했습니다.
.PP
\fB31\fR	Inflate 함수 호출중 오류가 발생했습니다.
.PP
\fB32\fR	사용자가 작업을 중단하였습니다.
.PP
\fB33\fR	압축 해제후 CRC 오류가 발생하였습니다.
.PP
\fB34\fR	모르는(혹은 지원하지 않는) 압축방식입니다.
.PP
\fB35\fR	암호걸린 파일인데 암호가 지정되지 않았습니다.
.PP
\fB36\fR	암호가 틀렸습니다.
.PP
\fB37\fR	파일 쓰다가 실패했습니다.
.PP
\fB38\fR	대상 파일을 만들 수 없습니다.
.PP
\fB39\fR	BZIP2 압축해제중 오류가 발생했습니다.
.PP
\fB40\fR	목적지 경로를 알수 없습니다. 경로명에 ../ 이 포함된 경우, 대상 경로에 접근이 불가능한 경우에 이러한 문제가 발생합니다.
.PP
\fB41\fR	경로 생성에 실패했습니다.
.PP
\fB42\fR	압축푸는데 데이타가 손상되었거나 RAR 분할 압축파일의 뒷부분이 없습니다.
.PP
\fB43\fR	쓰기용으로 파일 열기에 실패했습니다.
.PP
\fB44\fR	압축풀 대상의 index 파라메터가 잘못되었습니다.
.PP
\fB45\fR	압축 코덱의 헤더를 읽는데 오류가 있습니다.
.PP
\fB46\fR	코덱 초기화에 실패했습니다.
.PP
\fB47\fR	LZMA 압축 해제중 오류가 발생하였습니다.
.PP
\fB48\fR	ppmd와 관련된 오류가 있습니다.
.PP
\fB49\fR	출력 파일의 크기를 지정할수 없습니다.
.PP
\fB50\fR	압축을 푼 파일 크기가 맞지 않습니다.
.PP
\fB51\fR	분할 압축파일중 첫번째 파일이 아닙니다.
.PP
\fB52\fR	파일이 열려있지 않습니다.
.PP
\fB53\fR	지원하지 않는 암호 방식입니다.
.PP
\fB54\fR	알수 없는 내부 오류가 발생했습니다.
.PP
\fB55\fR	지원하지 않는 파일 포맷입니다.
.PP
\fB56\fR	압축파일이 아닙니다. 명백히 압축파일이 아닌 경우 발생됩니다.
.PP
\fB57\fR	경로명이 너무 길어서 파일이나 폴더를 만들 수 없습니다.
.PP
\fB58\fR	lz와 관련된 오류가 발생했습니다.
.PP
\fB59\fR	포함되지 않은 기능입니다.
.PP
\fB60\fR	파일을 쓰다가 실패했습니다.
.PP
\fB61\fR	파일의 뒷부분이 잘렸습니다.
.PP
\fB62\fR	압축 해제 작업중에는 파일을 열거나 닫을 수 없습니다.
.PP
\fB63\fR	분할 압축된 파일의 다음 파일을 찾을 수 없습니다.
.PP
\fB64\fR	압축파일이 아닙니다.
.PP
\fB65\fR	사용자가 건너띄기 했습니다.
.PP
\fB66\fR	암호가 틀리거나 파일이 손상되었습니다. (rar 포멧)
.PP
\fB67\fR	분할 zip 인데 마지막 zip 파일만 열려고 했습니다.
.PP
\fB68\fR	대상 폴더에 대해서 쓰기 권한이 없습니다.
.PP
\fB69\fR	메모리가 부족합니다.
.PP
\fB70\fR	LZMA 압축중 메모리가 부족합니다.
.PP
\fB71\fR	지원하지 않는 작동입니다(ACE 파일을 IArkSimpleOutStream 를 이용해 압축해제할 경우 발생합니다).
.PP
\fB72\fR	파일명이 잘못되어서 유니코드 파일명으로 바꿀 수 없습니다. 이 오류는 posix 환경에서 iconv 사용시 코드페이지가 잘못된 경우 사용할 수 없는 문자 때문에 발생합니다.
.PP
\fB73\fR	파일명이 너무 길어서 처리할 수 없습니다.
.PP
\fB74\fR	파일명이 너무 길어서 뒷부분이 잘렸습니다.
.PP
\fB75\fR	파일 갯수가 너무 길어서 처리할 수 없습니다.
.PP
\fB76\fR	파일이 손상되었습니다.
.PP
\fB77\fR	포맷이 다릅니다.
.PP
\fB78\fR	파일을 읽을 수 없습니다.
.PP
\fB79\fR	헤더파일과 dll 의 버전이 맞지 않습니다.
.PP
\fB80\fR	압축 해제 불가능합니다. 이 파일은 암호화된 bond 파일입니다.
.PP
\fB81\fR	7z.dll 으로 열때 오류가 발생했습니다. 이 파일은 깨진파일입니다.
.PP
\fB82\fR	7z.dll 열다가 오류가 발생했습니다.
.PP
\fB83\fR	파일을 쓰기용으로 생성하지 못합니다.
.PP
\fB84\fR	Init() 함수가 호출되지 않았습니다.
.PP
\fB85\fR	잘못된 파라메터로 호출하였습니다.
.PP
\fB86\fR	SFX 파일을 열지 못합니다.
.PP
\fB87\fR	SFX 파일의 크기가 4GB를 넘었습니다.
.PP
\fB88\fR	ArkXXLgpl.dll 파일을 열지 못합니다.
.PP
\fB89\fR	파일 크기가 4GB를 넘어서 저장할 수 없습니다.
.PP
\fB90\fR	이미 ARK DLL 파일을 로드하였습니다.
.PP
\fB91\fR	LoadLibrary() 함수를 호출하는데 실패했습니다.
.PP
\fB92\fR	GetProcAddress() 함수를 호출하는데 실패했습니다.
.PP
\fB93\fR	지원하지 않는 os입니다.
.PP
\fB94\fR	라이브러리를 로드하지 않았거나 로드하는데 실패하였습니다.
.PP
\fB95\fR	압축 해제에 관련된 기타 오류.
.PP
\fB96\fR	압축 파일의 경로에 문제가 있습니다.
.PP
\fB97\fR	현재 경로에 문제가 있습니다.

." ========================== 사용 가능한 코드 페이지 목록 ==========================
.SH 사용 가능한 코드 페이지 목록
쉼표로 구분된 이름은 해당 코드 페이지에 대한 별칭입니다. 각각의 단락은 동일한 코드 페이지의 이름이 나열된 공간이고, 쉼표로 구분된 각 단락의 첫번째 이름은 코드 페이지 번호를 의미한다. 두번째 이름 부터 해당 코드페이지에 대한 별칭을 의미한다.
." 아래 내용은 --codepage-list 옵션의 내용에 기반한다.
.PP
CP0, acp
.PP
CP1, oemcp
.PP
CP2, maccp
.PP
CP37, ibm037
.PP
CP437, ibm437
.PP
CP500, ibm500
.PP
CP708, asmo-708
.PP
CP709
.PP
CP710
.PP
CP720, dos-720
.PP
CP737, ibm737
.PP
CP775, ibm775
.PP
CP850, ibm850
.PP
CP852, ibm852
.PP
CP855, ibm855
.PP
CP857, ibm857
.PP
CP858, ibm00858
.PP
CP860, ibm860
.PP
CP861, ibm861
.PP
CP862, dos-862
.PP
CP863, ibm863
.PP
CP864, ibm864
.PP
CP865, ibm865
.PP
CP866, cp866
.PP
CP869, ibm869
.PP
CP870, ibm870
.PP
CP874, windows-874
.PP
CP875, cp875
.PP
CP932, shift_jis, shift-jis, jpn
.PP
CP936, gb2312
.PP
CP949, uhc, kor
.PP
CP950, big5
.PP
CP1026, ibm1026
.PP
CP1047, ibm01047
.PP
CP1140, ibm01140
.PP
CP1141, ibm01141
.PP
CP1142, ibm01142
.PP
CP1143, ibm01143
.PP
CP1144, ibm01144
.PP
CP1145, ibm01145
.PP
CP1146, ibm01146
.PP
CP1147, ibm01147
.PP
CP1148, ibm01148
.PP
CP1149, ibm01149
.PP
CP1200, utf-16, utf16, utf-16le, utf16le
.PP
CP1201, unicodefffe, utf-16be, utf16be
.PP
CP1250, windows-1250
.PP
CP1251, windows-1251
.PP
CP1252, windows-1252
.PP
CP1253, windows-1253
.PP
CP1254, windows-1254
.PP
CP1255, windows-1255
.PP
CP1256, windows-1256
.PP
CP1257, windows-1257
.PP
CP1258, windows-1258
.PP
CP1361, johab
.PP
CP10000, macintosh
.PP
CP10001, x-mac-japanese
.PP
CP10002, x-mac-chinesetrad
.PP
CP10003, x-mac-korean
.PP
CP10004, x-mac-arabic
.PP
CP10005, x-mac-hebrew
.PP
CP10006, x-mac-greek
.PP
CP10007, x-mac-cyrillic
.PP
CP10008, x-mac-chinesesimp
.PP
CP10010, x-mac-romanian
.PP
CP10017, x-mac-ukrainian
.PP
CP10021, x-mac-thai
.PP
CP10029, x-mac-ce
.PP
CP10079, x-mac-icelandic
.PP
CP10081, x-mac-turkish
.PP
CP10082, x-mac-croatian
.PP
CP12000, utf-32, utf32, utf32le, utf-32le
.PP
CP12001, utf-32be, utf32be
.PP
CP20000, x-chinese_cns
.PP
CP20001, x-cp20001
.PP
CP20002, x_chinese-eten
.PP
CP20003, x-cp20003
.PP
CP20004, x-cp20004
.PP
CP20005, x-cp20005
.PP
CP20105, x-ia5
.PP
CP20106, x-ia5-german
.PP
CP20107, x-ia5-swedish
.PP
CP20108, x-ia5-norwegian
.PP
CP20127, us-ascii
.PP
CP20261, x-cp20261
.PP
CP20269, x-cp20269
.PP
CP20273, ibm273
.PP
CP20277, ibm277
.PP
CP20278, ibm278
.PP
CP20280, ibm280
.PP
CP20284, ibm284
.PP
CP20285, ibm285
.PP
CP20290, ibm290
.PP
CP20297, ibm297
.PP
CP20420, ibm420
.PP
CP20423, ibm423
.PP
CP20424, ibm424
.PP
CP20833, x-ebcdic-koreanextended
.PP
CP20838, ibm-thai
.PP
CP20866, koi8-r
.PP
CP20871, ibm871
.PP
CP20880, ibm880
.PP
CP20905, ibm905
.PP
CP20924, ibm00924
.PP
CP20932, euc-jp
.PP
CP20936, x-cp20936
.PP
CP20949, x-cp20949
.PP
CP21025, cp1025
.PP
CP21027
.PP
CP21866, koi8-u
.PP
CP28591, iso-8859-1
.PP
CP28592, iso-8859-2
.PP
CP28593, iso-8859-3
.PP
CP28594, iso-8859-4
.PP
CP28595, iso-8859-5
.PP
CP28596, iso-8859-6
.PP
CP28597, iso-8859-7
.PP
CP28598, iso-8859-8
.PP
CP28599, iso-8859-9
.PP
CP28603, iso-8859-13
.PP
CP28605, iso-8859-15
.PP
CP29001, x-europa
.PP
CP38598, iso-8859-8-i
.PP
CP50220, iso-2022-jp
.PP
CP50221, csiso2022jp
.PP
CP50222, iso-2022-jp
.PP
CP50225, iso-2022-kr
.PP
CP50227, x-cp50227
.PP
CP50229
.PP
CP50930
.PP
CP50931
.PP
CP50933
.PP
CP50935
.PP
CP50936
.PP
CP50937
.PP
CP50939
.PP
CP51932, euc-jp
.PP
CP51936, euc-cn
.PP
CP51949, euc-kr
.PP
CP51950
.PP
CP52936, hz-gb-2312
.PP
CP54936, gb18030
.PP
CP57002, x-iscii-de
.PP
CP57003, x-iscii-be
.PP
CP57004, x-iscii-ta
.PP
CP57005, x-iscii-te
.PP
CP57006, x-iscii-as
.PP
CP57007, x-iscii-or
.PP
CP57008, x-iscii-ka
.PP
CP57009, x-iscii-ma
.PP
CP57010, x-iscii-gu
.PP
CP57011, x-iscii-pa
.PP
CP65000, utf-7, utf7
.PP
CP65001, utf-8, utf8

." ============================== 라이브러리 버전 정보 ==============================
.SH 라이브러리 버전 정보
ArkLibrary v5.0.2.3
.PP
libboost-program-options1.46.1
.PP
그 외의 라이브러리 버전 정보는 의존 패키지를 따릅니다.

." ============================== 저작권 ==============================
.SH 저작권
이 프로그램은 LGPL 3.0을 따릅니다. 라이센스 전문은
.I /usr/share/arkzip/COPYING
을 참조하여 주세요.
.PP
이 프로그램에 사용된 라이브러리에 대한 라이센스 정보는 
.I /usr/share/arkzip/License.txt
를 참조하여 주세요.

." ============================== 홈페이지 ==============================
.SH 홈페이지
https://github.com/Thestars3/arkzip

." ============================== 제작자 ==============================
.SH 제작자
별님 <w7dn1ng75r@gmail.com>
